custom_fields = {
	"Sales Order": [
		dict(
			fieldname="store",
			label="Store",
			fieldtype="Link",
			options="Store",
			insert_after="customer",
			in_list_view=1,
			in_standard_filter=1,
		),
		dict(
			fieldname="shipping_section",
			label="Ongkir (Invoice Terpisah)",
			fieldtype="Section Break",
			insert_after="store",
			collapsible=0,
		),
		dict(
			fieldname="shipping_amount",
			label="Biaya Ongkir",
			fieldtype="Currency",
			insert_after="shipping_section",
			description="Diisi jika order ini kena biaya kirim ke store. Saat Sales Order di-submit, otomatis dibuatkan Sales Invoice terpisah (Draft) untuk ongkir ini, terpisah dari invoice material.",
		),
		dict(
			fieldname="shipping_column_break",
			fieldtype="Column Break",
			insert_after="shipping_amount",
		),
		dict(
			fieldname="shipping_description",
			label="Catatan Ongkir",
			fieldtype="Small Text",
			insert_after="shipping_column_break",
		),
		dict(
			fieldname="store_shipping_charge",
			label="Store Shipping Charge",
			fieldtype="Link",
			options="Store Shipping Charge",
			insert_after="shipping_description",
			read_only=1,
		),
	],
	"POS Invoice": [
		dict(
			fieldname="store",
			label="Store",
			fieldtype="Link",
			options="Store",
			insert_after="pos_profile",
			in_list_view=1,
			in_standard_filter=1,
			allow_on_submit=1,
		),
		dict(
			fieldname="pos_reference",
			label="POS Reference",
			fieldtype="Data",
			insert_after="store",
			in_standard_filter=1,
			allow_on_submit=1,
			read_only=1,
			description="External transaction id from the store's own POS system, used to make repeated API calls idempotent.",
		),
	],
	"Sales Invoice": [
		dict(
			fieldname="store",
			label="Store",
			fieldtype="Link",
			options="Store",
			insert_after="pos_profile",
			in_list_view=1,
			in_standard_filter=1,
			allow_on_submit=1,
			depends_on="eval:doc.is_pos",
		),
		dict(
			fieldname="pos_reference",
			label="POS Reference",
			fieldtype="Data",
			insert_after="store",
			in_standard_filter=1,
			allow_on_submit=1,
			read_only=1,
			description="External transaction id from the store's own POS system, used to make repeated API calls idempotent.",
		),
	],
}
